// Run after build-storybook. Uses the same browser setup as check-dropdown.cjs.
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const { resolve } = require('node:path');
const { readdirSync } = require('node:fs');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = resolve(__dirname, '..');
const port = process.env.PICKER_TEST_PORT || '6237';
const base = `http://127.0.0.1:${port}`;
const server = spawn('python3', ['-m', 'http.server', port, '--bind', '127.0.0.1', '--directory', root], { stdio: 'ignore' });
let browser;
(async () => {
  try {
    for (let i = 0; i < 40; i++) {
      try { if ((await fetch(base)).ok) break; } catch {}
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    browser = await chromium.launch({ headless: true });
    for (const framework of ['react', 'vue']) {
      const page = await browser.newPage({ viewport: { width: 800, height: 700 } });
      const errors = [];
      page.on('pageerror', error => errors.push(error.message));
      page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
      const trigger = page.getByRole('button', { name: /^担当チーム/ });
      const panel = page.getByRole('group', { name: '担当チーム' });
      const search = page.getByRole('searchbox', { name: '担当チームを検索' });
      const list = page.getByRole('listbox', { name: '担当チーム' });
      const options = list.getByRole('option');
      const settle = () => page.waitForTimeout(80);
      const active = () => list.evaluate(el => document.getElementById(el.getAttribute('aria-activedescendant'))?.textContent?.trim());
      const story = async name => {
        await page.goto(`${base}/packages/${framework}/storybook-static/iframe.html?id=components-picker--${name}&viewMode=story`);
        await trigger.waitFor();
        await settle();
      };
      await story('default');
      assert.equal(await trigger.getAttribute('aria-expanded'), 'false');
      await trigger.click();
      await search.waitFor();
      await settle();
      assert(await search.evaluate(el => el === document.activeElement));
      assert.equal((await panel.boundingBox()).width, 200);
      const firstRow = await options.first().boundingBox();
      await page.mouse.move(firstRow.x - 2, firstRow.y + firstRow.height / 2);
      await options.first().hover();
      const highlight = list.locator(':scope > span').first();
      assert.equal(await list.evaluate(el => el.style.getPropertyValue('--highlight-opacity')), '1');
      assert((await highlight.evaluate(el => getComputedStyle(el).transitionProperty)).includes('transform'));
      await search.fill(' ＦＲＯＮＴ ');
      await settle();
      assert.equal(await options.count(), 1);
      assert.equal(await options.first().innerText(), 'Frontend');
      await search.press('Enter');
      await settle();
      assert.equal(await trigger.innerText(), 'Frontend');
      assert.equal(await trigger.getAttribute('aria-expanded'), 'false');
      assert(await trigger.evaluate(el => el === document.activeElement));
      await trigger.click();
      await settle();
      assert.equal(await search.inputValue(), '');
      assert.equal(await options.count(), 6);
      assert.equal(await list.getByRole('option', { selected: true }).innerText(), 'Frontend');
      await search.fill('ﾃﾞｻﾞｲﾝ');
      await settle();
      assert.equal(await options.count(), 1);
      // Composition-confirming Enter must not accidentally select or close.
      await search.dispatchEvent('keydown', { key: 'Enter', isComposing: true });
      await search.dispatchEvent('keydown', { key: 'Enter', keyCode: 229 });
      assert.equal(await trigger.getAttribute('aria-expanded'), 'true');
      await search.fill('存在しないチーム');
      await settle();
      assert.equal(await options.count(), 0);
      assert(await page.getByRole('status').isVisible());
      await search.press('ArrowDown');
      await search.press('Enter');
      assert(await search.evaluate(el => el === document.activeElement));
      await search.press('Escape');
      await trigger.press('ArrowDown');
      await settle();
      await search.press('ArrowDown');
      await settle();
      assert(await list.evaluate(el => el === document.activeElement));
      assert.equal(await active(), 'Frontend');
      await list.press('Home');
      await settle();
      assert.equal(await active(), 'デザイン');
      await list.press('ArrowDown');
      await list.press('ArrowDown');
      await list.press('ArrowDown');
      await settle();
      assert.equal(await active(), 'レビュー', 'skip disabled options');
      await list.press('End');
      await settle();
      assert.equal(await active(), '公開');
      await list.press('Shift+Tab');
      assert(await search.evaluate(el => el === document.activeElement));
      await search.press('Tab');
      await list.press('Tab');
      await settle();
      assert.equal(await trigger.getAttribute('aria-expanded'), 'false');

      await story('multiple-selection');
      assert.equal(await list.getAttribute('aria-multiselectable'), 'true');
      await search.fill('end');
      await settle();
      assert.equal(await options.count(), 2);
      await options.nth(0).click();
      await settle();
      assert.equal(await trigger.innerText(), 'デザイン、Frontend');
      await options.nth(1).click();
      await settle();
      assert.equal(await trigger.innerText(), 'デザイン、Frontend、Backend');
      assert.equal(await trigger.getAttribute('aria-expanded'), 'true');
      assert.equal(await options.nth(1).getAttribute('data-grow-top'), 'true');
      await list.press(' ');
      await settle();
      assert.equal(await trigger.innerText(), 'デザイン、Frontend');
      await search.fill('');
      await settle();
      assert.equal(await list.getByRole('option', { selected: true }).count(), 2);
      await options.nth(3).click({ force: true });
      assert.equal(await list.getByRole('option', { selected: true }).count(), 2);
      // Menu width is independent of a long trigger and stretched parent.
      await trigger.evaluate(el => { el.parentElement.style.width = '600px'; });
      assert.equal((await panel.boundingBox()).width, 200);
      const axe = readdirSync(`${root}/node_modules/.pnpm`).find(name => name.startsWith('axe-core@'));
      await page.addScriptTag({ path: `${root}/node_modules/.pnpm/${axe}/node_modules/axe-core/axe.min.js` });
      assert.deepEqual(await page.evaluate(async () => (await axe.run(document.querySelector('#storybook-root'))).violations.map(v => v.id)), []);
      await page.emulateMedia({ reducedMotion: 'reduce' });
      assert.equal(await options.first().locator(':scope > span').first().evaluate(el => getComputedStyle(el, '::before').transitionDuration), '0s');
      await page.emulateMedia({ reducedMotion: 'no-preference' });
      await page.mouse.click(700, 500);
      assert.equal(await trigger.getAttribute('aria-expanded'), 'false');

      await story('controlled');
      await trigger.click();
      await search.waitFor();
      await options.first().click();
      await settle();
      assert.equal(await trigger.innerText(), 'デザイン');
      assert.equal(await page.locator('output').innerText(), '選択: design');
      await page.getByRole('button', { name: '選択をクリア' }).click();
      await settle();
      assert.equal(await trigger.innerText(), '担当チーム');
      await trigger.click();
      await settle();
      assert.equal(await list.getByRole('option', { selected: true }).count(), 0);

      await story('empty');
      await page.waitForTimeout(350);
      assert.equal(await page.getByRole('status').innerText(), '項目がありません');
      await search.press('Enter');
      assert.equal(await trigger.getAttribute('aria-expanded'), 'true');
      await story('all-disabled');
      await search.press('ArrowDown');
      await search.press('Enter');
      assert(await search.evaluate(el => el === document.activeElement));
      assert.equal(await list.getByRole('option', { selected: true }).count(), 0);
      await story('disabled');
      assert(await trigger.isDisabled());
      assert.equal(await trigger.getAttribute('aria-expanded'), 'false');
      await story('no-icon');
      assert.equal(await trigger.locator('svg').count(), 0);
      await story('custom-icon');
      assert.equal(await trigger.locator('svg circle').count(), 3);

      await story('scrollable');
      const inputTop = (await search.boundingBox()).y;
      await search.press('ArrowDown');
      await list.press('End');
      await settle();
      assert.equal(await active(), 'チーム 30');
      assert(await list.evaluate(el => el.scrollTop > 0));
      assert.equal((await search.boundingBox()).y, inputTop, 'search stays visible while the list scrolls');
      await story('bottom-edge');
      assert.equal(await panel.getAttribute('data-side'), 'top');
      await search.press('ArrowDown');
      await settle();
      for (const width of [320, 210, 180]) {
        await page.setViewportSize({ width, height: 360 });
        await settle();
        const bounds = await panel.boundingBox();
        assert(bounds.x >= 7 && bounds.x + bounds.width <= width - 7);
        assert(bounds.width <= Math.min(200, width - 32));
        assert(await panel.evaluate(el => el.scrollWidth <= el.clientWidth));
        assert(await list.evaluate(el => parseFloat(el.style.getPropertyValue('--highlight-width')) === el.querySelector('[data-active="true"]').offsetWidth));
      }
      await page.setViewportSize({ width: 800, height: 700 });
      await story('two-pickers');
      const firstId = await trigger.getAttribute('aria-controls');
      const second = page.getByRole('button', { name: '確認チーム' });
      assert.notEqual(await second.getAttribute('aria-controls'), firstId);
      await trigger.click();
      await settle();
      await second.click();
      await settle();
      assert.equal(await trigger.getAttribute('aria-expanded'), 'false');
      assert(await page.getByRole('searchbox', { name: '確認チームを検索' }).evaluate(el => el === document.activeElement));

      await story('without-search');
      assert.equal(await search.count(), 0);
      assert.equal(await trigger.getAttribute('aria-haspopup'), 'listbox');
      assert.equal(await trigger.getAttribute('aria-controls'), await list.getAttribute('id'));
      assert(await list.evaluate(el => el === document.activeElement));
      assert.equal(await active(), 'Frontend');
      assert.equal(await trigger.innerText(), 'Frontend');
      await list.press('b');
      await settle();
      assert.equal(await active(), 'Backend', 'typeahead works without a search input');
      await list.press('Enter');
      await settle();
      assert.equal(await trigger.innerText(), 'Backend');
      assert.equal(await trigger.getAttribute('aria-label'), '担当チーム: Backend');
      assert.equal(await trigger.getAttribute('aria-expanded'), 'false');
      assert(await trigger.evaluate(el => el === document.activeElement));
      await trigger.press('ArrowUp');
      await settle();
      assert.equal(await active(), '公開');
      await list.press('Escape');

      await story('multiple-without-search');
      assert.equal(await search.count(), 0);
      assert.equal(await list.getByRole('option', { selected: true }).count(), 1);
      await options.nth(1).click();
      await settle();
      assert.equal(await trigger.innerText(), 'デザイン、Frontend');
      assert.equal(await trigger.getAttribute('aria-expanded'), 'true');
      assert.equal((await panel.boundingBox()).width, 200);
      const background = row => row.locator(':scope > span').first();
      const scale = (row, pseudo = '::before') => background(row).evaluate((el, pseudo) =>
        new DOMMatrixReadOnly(getComputedStyle(el, pseudo).transform).d, pseudo);
      await page.waitForTimeout(300);
      assert.equal(await background(options.first()).evaluate(el => getComputedStyle(el).borderBottomLeftRadius), '0px');
      const check = options.nth(1).locator(':scope > span').last();
      assert.equal(await check.evaluate(el => getComputedStyle(el).opacity), '1');
      const rowBox = await options.nth(1).boundingBox();
      const checkBox = await check.boundingBox();
      assert.equal(rowBox.x + rowBox.width - checkBox.x - checkBox.width, 10);
      await list.press('Space');
      await settle();
      assert.equal(await trigger.innerText(), 'デザイン');
      await list.press('Escape');
      await trigger.click();
      await settle();
      assert.equal(await list.getByRole('option', { selected: true }).count(), 1);

      await story('adjacent-selection');
      await page.waitForTimeout(350);
      await options.nth(1).click();
      await page.waitForTimeout(50);
      const top = await scale(options.nth(1));
      const bottom = await scale(options.nth(1), '::after');
      assert(top > 0 && top < 0.5, 'selection grows from the selected neighbour above');
      assert(bottom > 0 && bottom < 0.5, 'selection grows from the selected neighbour below');
      await page.waitForTimeout(300);
      assert.equal(await scale(options.nth(1)), 0.5);
      assert.equal(await scale(options.nth(1), '::after'), 0.5);
      await options.nth(1).click();
      await page.waitForTimeout(300);
      assert.equal(await scale(options.nth(1)), 0);
      assert.equal(await background(options.first()).evaluate(el => getComputedStyle(el).borderBottomLeftRadius), '8px');
      assert.equal(await background(options.nth(2)).evaluate(el => getComputedStyle(el).borderTopLeftRadius), '8px');
      await options.first().click();
      await options.nth(1).click();
      await settle();
      assert.equal(await options.nth(1).getAttribute('data-grow-bottom'), 'true');
      assert.equal(await options.nth(1).getAttribute('data-grow-top'), 'false');
      await page.addScriptTag({ path: `${root}/node_modules/.pnpm/${axe}/node_modules/axe-core/axe.min.js` });
      assert.deepEqual(await page.evaluate(async () => (await axe.run(document.querySelector('#storybook-root'))).violations.map(v => v.id)), []);

      await story('controlled-without-search');
      await trigger.click();
      await list.waitFor();
      await options.first().click();
      await settle();
      assert.equal(await page.locator('output').innerText(), '選択: design');
      await page.getByRole('button', { name: '選択をクリア' }).click();
      await settle();
      assert.equal(await trigger.innerText(), '担当チーム');
      await story('empty-without-search');
      assert.equal(await search.count(), 0);
      await page.waitForTimeout(350);
      assert.equal(await page.getByRole('status').innerText(), '項目がありません');
      assert(await trigger.evaluate(el => el === document.activeElement));
      await trigger.press('Escape');
      assert.equal(await trigger.getAttribute('aria-expanded'), 'false');
      assert.deepEqual(errors, []);
      await page.close();
      console.log(`${framework}: Picker with/without search, IME, selection/merging, keyboard, focus, sizing, placement, scrolling and accessibility passed`);
    }
  } finally {
    await browser?.close();
    server.kill();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
